### ISSUE TITLE
Release the working LAC version

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/stable-learning-control#18]
## User story

We want to release the working LAC solution to the Machine_Learning_Control framework.

### LAC
- Release only PyTorch version or also tf2 eager version?
    - For now, we include both PyTorch and tf2.
- Do we want to use the spinning up logger or the LAC original logger. 
     - We can also supply both print formats. Meaning defaults to our MLC format and then people can switch by using `"spinningup"` in the format logger argument.
- I think including short documentation on the LAC algorithm like this is done in the spinning [SAC algorithm](https://spinningup.openai.com/en/latest/algorithms/sac.html) is important.
- Do you want me to include a reference statement in the lac algorithm folder README.md to the LAC article?
    - See [spinningup](https://github.com/openai/spinningup) for example.
- Currently, the following features are not included:
    - [ ] [Different time horizon.](https://github.com/rickstaa/filter_LAC_tf_rewrite/blob/4b18fb3761bf4f76d66299659e88eb8d756ee69e/LAC/LAC_V1.py#L60)
        - Might be useful for people who want to use the LAC article.

#### Panda
- [ ] Needs a small clean up session before adding it.
    - Currently due to the development timeline supports both End effector control, joint_position control and joint_effort control. Shall we keep all these modes of control or can we get rid of the Joint effort control?

#### EX3_EKF
- [ ] Shall we add this environment?

## Release Todos
- [x] Add the Ex3_EKF and oscillator environments.
- [x] Add the department logging format to the logger.
- [ ] Add the configuration files to the MLC package.
- [x] #23 Validate whether the LAC torch version has the same performance as the LAC TF1 version.
- [x] Validate the algorithm speed.
- [ ] Transform the SAC function to a class.
- [x] Add the LAC algorithm.
- [ ] Transform the LAC script to a class. 
- [ ] #22 Check the difference in the replay buffer between LAC TF1 and Spinning up.
- [x] #19 Check log inf NaN problem.
- [ ] Add the robustness eval script.
- [ ] Add the hyperparameter tuning script.
- [ ] Compile the documentation
    - [ ] Add installation steps to the docs.
    - [ ] Add additional configuration file run steps to the docs.
    - [ ] Compile the automatically generated API documentation
- [ ] Update the version.
- [ ] Draft the first release.
