### ISSUE TITLE
Add torch LAC version

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/stable-learning-control#90]
Add the https://github.com/rickstaa/LAC-TF2-TORCH-translation/tree/master/LAC_TORCH version.

### Todos
- [x] Add LAC class.
- [x] Validate training script.
- [x] Add inference script.
- [x] Update logger.
- [x] Update replay buffer to new version.
