### ISSUE TITLE
Add tf2 LAC version

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/stable-learning-control#91]
Adds https://github.com/rickstaa/LAC-TF2-TORCH-translation/tree/master/LAC_TF2.

### Todos
- [x] Add LAC class.
- [x] Validate training script.
- [x] Add inference script.
- [x] Update logger.
- [x] Update replay buffer to new version.
